# Sprint 12. APIs REST

Aplicarás lo aprendido sobre APIs REST, métodos HTTP y códigos de estado, utilizando APIs públicas para consultar datos, filtrarlos y finalmente guardarlos en un DataFrame de pandas.

In [31]:
import requests
import pandas as pd

## Nivel 1

Desde un Jupyter Notebook realizarás los siguientes ejercicios utilizando la librería requests de Python.

Exploración básica con una API de laboratorio.

### 1. 
Consulta la API pública JSONPlaceholder utilizando el método GET para obtener:

* Lista de publicaciones
* Lista de usuarios (/users)
* Lista de tareas (/todos)

In [32]:
BASE= "https://jsonplaceholder.typicode.com" # URL base


endpoints = {"Posts": f"{BASE}/posts", # diccionario que contiene los endpoints a consultar
            "Users": f"{BASE}/users",
            "ToDos": f"{BASE}/todos"}

data = {} # diccionario para almacenar las respuestas JSON

for nombre, enlace in endpoints.items(): # recorrer cada endpoint
    GET = requests.get(enlace) # hacer una llamada GET 
    
    json_data = GET.json() # convertir a JSON la información recibida
    
    data[nombre] = json_data # guardar el resultado en el diccionario
    
    print(f"{nombre}") # nombre del endpoint
    print(f"URL: {enlace}") # enlace para acceder al endpoint
    print(f"Primer elemento de {nombre}:")
    print(json_data[0])
    print("_" * 200)

Posts
URL: https://jsonplaceholder.typicode.com/posts
Primer elemento de Posts:
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
________________________________________________________________________________________________________________________________________________________________________________________________________
Users
URL: https://jsonplaceholder.typicode.com/users
Primer elemento de Users:
{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}
________________________________________________________________________________________________________________________________________________________________________________________________________
ToDos
URL: https://jsonplaceholder.typicode.com/todos
Primer elemento de ToDos:
{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}
________________________________________________________________________________________________________________________________________________________________________________________________________

### 2. 
Muestra por pantalla:

* La cantidad total de cada recurso.
* El código de estado de cada petición.

In [33]:
for nombre, enlace in endpoints.items(): # recorrer cada endpoint
    GET = requests.get(enlace)
    
    estado = GET.status_code # recibir el código de estado
    json_data = GET.json()
    cantidad_items = len(json_data) # cantidad total de elementos de endpoint
    
    print(f"Recurso: {nombre}")
    print(f"URL consultada: {enlace}")
    print(f"Código de estado HTTP: {estado}")
    print(f"Cantidad total de elementos: {cantidad_items}")
    print("_" * 200)

Recurso: Posts
URL consultada: https://jsonplaceholder.typicode.com/posts
Código de estado HTTP: 200
Cantidad total de elementos: 100
________________________________________________________________________________________________________________________________________________________________________________________________________
Recurso: Users
URL consultada: https://jsonplaceholder.typicode.com/users
Código de estado HTTP: 200
Cantidad total de elementos: 10
________________________________________________________________________________________________________________________________________________________________________________________________________
Recurso: ToDos
URL consultada: https://jsonplaceholder.typicode.com/todos
Código de estado HTTP: 200
Cantidad total de elementos: 200
________________________________________________________________________________________________________________________________________________________________________________________________________

### 3. 
Realiza una petición a una publicación inexistente para obtener un error 404 y muestra el código de estado recibido.

In [34]:
inexistente=f"{BASE}/posts/inexistente"

GET = requests.get(inexistente) # petición GET a un recurso inexistente 

estado = GET.status_code # solicitar el código de estado

print(f"URL: {inexistente}")
print(f"Código de estado HTTP: {estado}")

URL: https://jsonplaceholder.typicode.com/posts/inexistente
Código de estado HTTP: 404

### 4. 
Realiza una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.

* Muestra la respuesta JSON.
* Muestra el código de estado.

In [35]:
posts = f"{BASE}/posts"

payload = {"title": "Post 1",
            "body": "Blah blah blah.. ",
            "userId": 1}

POST = requests.post(posts, json=payload) # petición POST (URL + diccionario)

status_code = POST.status_code # el código de estado

response_json = POST.json() # convertir la respuesta a JSON

print("Petición POST para crear una nueva publicación ficticia")
print("_" * 200)
print(f"URL: {posts}")
print("Datos enviados:")
print(payload)
print("_" * 200)
print("Respuesta JSON recibida:")
print(response_json)
print("_" * 200)
print(f"Código de estado HTTP: {status_code}")

Petición POST para crear una nueva publicación ficticia
________________________________________________________________________________________________________________________________________________________________________________________________________
URL: https://jsonplaceholder.typicode.com/posts
Datos enviados:
{'title': 'Post 1', 'body': 'Blah blah blah.. ', 'userId': 1}
________________________________________________________________________________________________________________________________________________________________________________________________________
Respuesta JSON recibida:
{'title': 'Post 1', 'body': 'Blah blah blah.. ', 'userId': 1, 'id': 101}
________________________________________________________________________________________________________________________________________________________________________________________________________
Código de estado HTTP: 201

### 5. 
Realiza una petición PATCH para modificar parcialmente una publicación existente.

* Muestra la respuesta JSON.
* Muestra el código de estado.

In [36]:
post_id = 1
enlace_post = f"{BASE}/posts/{post_id}"

payload = {"title": "Título modificado con PATCH"} # el nuevo título

PATCH = requests.patch(enlace_post, json=payload) # realizar la petición PATCH (enlace + cambio)

estado = PATCH.status_code # obtener el código de estado

PATCH_json = PATCH.json() # convertir la respuesta a JSON

print("Petición PATCH para modificar parcialmente una publicación")
print(f"URL: {enlace_post}")
print("Datos enviados:")
print(payload)
print("_" * 200)
print("Respuesta JSON recibida:")
print(PATCH_json)
print("_" * 200)
print(f"Código de estado HTTP: {estado}")

Petición PATCH para modificar parcialmente una publicación
URL: https://jsonplaceholder.typicode.com/posts/1
Datos enviados:
{'title': 'Título modificado con PATCH'}
________________________________________________________________________________________________________________________________________________________________________________________________________
Respuesta JSON recibida:
{'userId': 1, 'id': 1, 'title': 'Título modificado con PATCH', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
________________________________________________________________________________________________________________________________________________________________________________________________________
Código de estado HTTP: 200

### 6. Haz una petición DELETE sobre una publicación.

* Muestra la respuesta JSON.
* Muestra el código de estado.

In [ ]:
post_id = 1
url_post = f"{BASE}/posts/{post_id}"

DELETE = requests.delete(url_post)# realizar la petición DELETE

estado = DELETE.status_code # obtener el código de estado

DELETE_json = DELETE.json() # convertir a JSON

print("Petición DELETE para eliminar una publicación")
print(f"URL: {url_post}")
print("_" * 200)
print("JSON recibido:")
print(DELETE_json)
print("_" * 200)
print(f"Código de estado HTTP recibido: {estado}")

Petición DELETE para eliminar una publicación
URL: https://jsonplaceholder.typicode.com/posts/1
________________________________________________________________________________________________________________________________________________________________________________________________________
JSON recibido:
{}
________________________________________________________________________________________________________________________________________________________________________________________________________
Código de estado HTTP recibido: 200

## Nivel 2

### 1. 
Explora el repositorio de Public APIs y elige una API que permita realizar peticiones GET.

**Motivos de la elección**

> He elegido la API pública **EmojiHub**

> - Es una API REST pública y gratuita.
> - No requiere autenticación ni clave de acceso.
> - Permite realizar peticiones GET.
> - Devuelve datos en formato JSON.
> - Proporciona información estructurada (nombre del emoji, categoría, grupo y códigos Unicode).

### 2.
Lee la documentación de la API:

* Revisa la sección de endpoints disponibles. En un markdown, apunta al menos dos endpoints diferentes.

**Endpoints disponibles**

> 1. `GET /api/random`  
   Devuelve un emoji aleatorio junto con su información (nombre, categoría, grupo, Unicode, etc.).

> 2. `GET /api/all`  
   Devuelve la lista completa de emojis disponibles.

> 3. `GET /api/category/{category}`  
   Devuelve todos los emojis que pertenecen a una categoría.

> 4. `GET /api/group/{group}`  
   Devuelve todos los emojis que pertenecen a un grupo dentro de una categoría.

* Comprueba si ofrece filtros o parámetros opcionales interesantes. En un markdown, anótalos.

**Filtros o parámetros opcionales**

> La API EmojiHub permite filtrar resultados mediante parámetros incluidos en la propia URL (path parameters):

> - `/api/category/{category}` - filtra emojis por categoría
> - `/api/group/{group}` - filtra emojis por grupo

> Lo que permite obtener subconjuntos de datos sin necesidad de descargar la colección completa de emojis.

* Verifica que la respuesta sea en formato JSON (es el más adecuado para este ejercicio).

**Formato de la respuesta**

> La API EmojiHub devuelve los datos en formato <ins>JSON</ins>

`https://emojihub.yurace.pro/api/random`

> {
  "name": "black small square",
  "category": "symbols",
  "group": "symbols",
  "htmlCode": [
    "&#9642;"
  ],
  "unicode": [
    "U+25AA"
  ]
}

### 3.
Haz una petición GET sencilla:

* Muestra el código de estado de la respuesta.
* Imprime de forma clara algunos de los campos de la respuesta JSON.

In [38]:
url = "https://emojihub.yurace.pro/api/random" # URL del endpoint seleccionado

GET = requests.get(url) # realizar la petición GET

print("Código de estado HTTP:", GET.status_code) # mostrar el código de estado HTTP

emoji = GET.json() # convertir a JSON

print("\nCampos JSON:")
print("_" * 12)
print("Nombre del emoji:", emoji.get("name"))
print("Categoría:", emoji.get("category"))
print("Grupo:", emoji.get("group"))
print("Unicode:", emoji.get("unicode"))

Código de estado HTTP: 200

Campos JSON:
____________
Nombre del emoji: squared katakana sa
Categoría: symbols
Grupo: symbols
Unicode: ['U+1F202']

### 4. 
Convierte los datos a un DataFrame de pandas:

* Muestra las primeras filas de DataFrame

In [39]:
df = pd.DataFrame([emoji]) # convertir JSON a un DataFrame

print("Primeras filas del DataFrame:")
display(df.head())

Primeras filas del DataFrame:

                  name category    group     htmlCode    unicode
0  squared katakana sa  symbols  symbols  [&#127490;]  [U+1F202]

## Nivel 3

### 1. 
Utiliza la API de Open Data BCN para:

* Buscar un dataset de tu interés mediante package_search y package_show.

> *Open Data BCN* emplea el software CKAN permite buscar y obtener detalles de conjuntos de datos mediante los endpoints package_search y package_show.

> He realizado una búsqueda usando la palabra clave *"aeroport"* para encontrar datasets relacionados con el aeropuerto Josep Tarradellas Barcelona‑El Prat.


> Los endpoints usados son:
> - package_search: para buscar datasets por texto
> - package_show: para obtener información completa de un dataset a partir de su ID

In [40]:
BASE = "https://opendata-ajuntament.barcelona.cat/data/api/3/action" # enlace de Open Data BCN

# 1) Búsqueda de datasets que contengan "aeroport"
palabra = "aeroport"
enlace = f"{BASE}/package_search?q={palabra}"

busqueda = requests.get(enlace) # petición GET

print("Código de estado de package_search:", busqueda.status_code) # código de estado
busqueda_json = busqueda.json() # cambio a JSON

total_resultados = busqueda_json["result"]["count"] # número total de resultados
print("Total de resultados encontrados:", total_resultados)

primer_dataset = busqueda_json["result"]["results"][0] # el primer dataset de resultados
dataset_id = primer_dataset["id"]
dataset_nombre = primer_dataset.get("name", "")

print("ID del primer dataset encontrado:", dataset_id)
print("Nombre del primer dataset:", dataset_nombre)

print("\nPrimer dataset (resumen):")
print(primer_dataset) # ejemplo del dataset

# 2) Obtener los detalles completos con package_show
show_url = f"{BASE}/package_show?id={dataset_id}"
respuesta_show = requests.get(show_url)

print("\nStatus code de package_show:", respuesta_show.status_code)

show_json = respuesta_show.json()

print("\nDetalles completos del datase:")
print(show_json)

Código de estado de package_search: 200
Total de resultados encontrados: 4
ID del primer dataset encontrado: 6ea9c163-e907-49fc-b916-bdddd1448e9e
Nombre del primer dataset: transitaeri_flightradar_ppal_pais

Primer dataset (resumen):
{'notes_translated': {'ca': "Nombre d'operacions d'aeronaus de l'aeroport Josep Tarradellas Barcelona-El Prat per principals països de destinació o origen   ", 'en': 'Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries', 'es': 'Número de operaciones de aeronaves del aeropuerto Josep Tarradellas Barcelona-El Prat por principales países de destino u origen'}, 'geolocation': 'No', 'dades_alt_valor': 'Estadistica', 'url_tornada': {'ca': '', 'en': '', 'es': ''}, 'dataset_fields_description': "__NOTA:__ La publicació d'aquestes dades queda interrompuda el 5/1/2025. \r\nEsperem poder restablir-la el més aviat possible. Perdoneu les molèsties ocasionades.", 'fuente': 'Flightradar24', 'tag': 'Vols,Aeroport,Companyies aèries,Any 2019,Any 2020,Any 2021,Any 2022,Any 2023,Any 2024,Països,Any 2025,Alt Valor', 'private': False, 'num_tags': 12, 'code': 'TransitAeri_FlightRadar_Ppal_Pais', 'frequency': 'MENSUAL', 'id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'title_translated': {'ca': "Nombre d'operacions d'aeronaus de l'aeroport Josep Tarradellas Barcelona-El Prat per principals països de destinació o origen   ", 'en': 'Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries', 'es': 'Número de operaciones de aeronaves del aeropuerto Josep Tarradellas Barcelona-El Prat por principales países de destino u origen'}, 'metadata_modified': '2025-09-23T11:38:56.549389', 'author': 'Gerència Municipal', 'author_email': None, 'isopen': True, 'long_format': 'Yes', 'state': 'active', 'version': '', 'mar_od': 'Yes', 'relationships_as_object': [], 'department': "Oficina Municipal de Dades - Departament d'Estadística i Difusió de Dades", 'creator_user_id': '6d593275-d059-4261-9004-e6df8677e3bf', 'type': 'dataset', 'resources': [{'cache_last_updated': None, 'package_id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'datastore_active': True, 'id': 'daaf92f4-8879-40f0-bc35-d550f1f9582a', 'api_access_number_absolute': '13', 'state': 'active', 'api_access_number': '13', 'size': '3362', 'hash': '', 'description': '', 'format': 'CSV', 'downloads': '84', 'last_modified': None, 'url_type': None, 'mimetype': None, 'cache_url': None, 'name': '2025_TransitAeri_FlightRadar_Ppal_Pais.csv', 'created': '2025-03-26T09:00:20.385158', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/daaf92f4-8879-40f0-bc35-d550f1f9582a/download', 'downloads_absolute': '89', 'qa': '{\'updated\': \'2026-01-27T02:17:26.370541\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-03-27T02:13:38.584219\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'mimetype_inner': None, 'position': 0, 'revision_id': '7a87bddf-d3d5-4944-b97f-ea67a7b36a8e', 'resource_type': None}, {'api_access_number_absolute': '49', 'cache_last_updated': None, 'token_type': '', 'package_id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'datastore_active': True, 'id': '9b10dc6e-9266-4e33-935e-e10ed0dae343', 'description': ' ', 'state': 'active', 'api_access_number': '20', 'size': '242404', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '252', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'column_types': '', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2024_TransitAeri_FlightRadar_Ppal_Pais.csv', 'created': '2024-05-29T09:31:06.756252', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/9b10dc6e-9266-4e33-935e-e10ed0dae343/download', 'downloads_absolute': '392', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-01-27T02:17:26.401397\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-05-31T02:08:40.233667\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': None, 'position': 1, 'revision_id': '7a87bddf-d3d5-4944-b97f-ea67a7b36a8e', 'resource_type': None}, {'api_access_number_absolute': '2', 'cache_last_updated': None, 'token_type': '', 'package_id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'datastore_active': True, 'id': '89cfba93-a038-4afe-adf5-599d879966d8', 'description': ' ', 'state': 'active', 'api_access_number': '2', 'size': '240300', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '128', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'column_types': '', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2023_TransitAeri_FlightRadar_Ppal_Pais.csv', 'created': '2024-05-29T09:31:49.618462', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/89cfba93-a038-4afe-adf5-599d879966d8/download', 'downloads_absolute': '149', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-01-27T02:17:26.421156\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-05-31T02:08:40.244994\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': None, 'position': 2, 'revision_id': '7a87bddf-d3d5-4944-b97f-ea67a7b36a8e', 'resource_type': None}, {'api_access_number_absolute': '2', 'cache_last_updated': None, 'token_type': '', 'package_id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'datastore_active': True, 'id': '1d78cf40-9d04-4be0-bcee-8e075c9a77a0', 'description': '', 'state': 'active', 'api_access_number': '2', 'size': '237692', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '87', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'column_types': '', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2022_TransitAeri_FlightRadar_Ppal_Pais.csv', 'created': '2024-05-29T09:32:06.818210', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/1d78cf40-9d04-4be0-bcee-8e075c9a77a0/download', 'downloads_absolute': '94', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-01-27T02:17:26.440808\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-05-31T02:08:40.262138\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': None, 'position': 3, 'revision_id': '7a87bddf-d3d5-4944-b97f-ea67a7b36a8e', 'resource_type': None}, {'api_access_number_absolute': '2', 'cache_last_updated': None, 'token_type': '', 'package_id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'datastore_active': True, 'id': 'c402f60b-5fb8-437a-bbbe-8976ac7ede51', 'description': '', 'state': 'active', 'api_access_number': '2', 'size': '196089', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '72', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'column_types': '', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2021_TransitAeri_FlightRadar_Ppal_Pais.csv', 'created': '2024-05-29T09:32:24.031098', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/c402f60b-5fb8-437a-bbbe-8976ac7ede51/download', 'downloads_absolute': '73', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-01-27T02:17:26.472947\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-05-31T02:08:40.272246\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': None, 'position': 4, 'revision_id': '7a87bddf-d3d5-4944-b97f-ea67a7b36a8e', 'resource_type': None}, {'api_access_number_absolute': '2', 'cache_last_updated': None, 'token_type': '', 'package_id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'datastore_active': True, 'id': '6d34a732-bdad-49e2-8231-7459120896d2', 'description': '', 'state': 'active', 'api_access_number': '2', 'size': '159092', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '70', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'column_types': '', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2020_TransitAeri_FlightRadar_Ppal_Pais.csv', 'created': '2024-05-29T09:32:42.636403', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/6d34a732-bdad-49e2-8231-7459120896d2/download', 'downloads_absolute': '81', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-01-27T02:17:26.502655\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-05-31T02:08:40.282041\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': None, 'position': 5, 'revision_id': '7a87bddf-d3d5-4944-b97f-ea67a7b36a8e', 'resource_type': None}, {'api_access_number_absolute': '5', 'cache_last_updated': None, 'token_type': '', 'package_id': '6ea9c163-e907-49fc-b916-bdddd1448e9e', 'datastore_active': True, 'id': '790b7bb3-cc2a-48d7-82c0-ef51978bceb7', 'description': '', 'state': 'active', 'api_access_number': '4', 'size': '121362', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '81', 'mimetype_inner': None, 'url_type': None, 'token_provider': '', 'column_types': '', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2019_TransitAeri_FlightRadar_Ppal_Pais.csv', 'created': '2024-05-29T09:33:04.915555', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/790b7bb3-cc2a-48d7-82c0-ef51978bceb7/download', 'downloads_absolute': '83', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-01-27T02:17:26.523471\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2024-05-31T02:08:40.293933\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': None, 'position': 6, 'revision_id': '7a87bddf-d3d5-4944-b97f-ea67a7b36a8e', 'resource_type': None}], 'token_required': 'No', 'decalatgeNum': '1', 'tags': [{'vocabulary_id': None, 'state': 'active', 'display_name': 'Aeroport', 'id': 'd07cfad1-126e-4779-a8af-1b1f3a118668', 'name': 'Aeroport'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Alt Valor', 'id': 'ebe20eba-8f65-40a9-9c25-4e7ab62b8f45', 'name': 'Alt Valor'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Any 2019', 'id': '4fdbddac-00a9-480e-a846-8148522b3500', 'name': 'Any 2019'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Any 2020', 'id': '2ff883a0-d01a-4af3-8235-8407a6e411a7', 'name': 'Any 2020'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Any 2021', 'id': '28ab7cce-e938-4cca-adc6-800b03070775', 'name': 'Any 2021'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Any 2022', 'id': '224016e4-81b8-4e60-819b-e7119ced7589', 'name': 'Any 2022'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Any 2023', 'id': '3f5176c6-4773-426d-b3f4-729d7d47f59d', 'name': 'Any 2023'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Any 2024', 'id': '283fc2f8-cbae-4ef0-9884-edf991193b9f', 'name': 'Any 2024'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Any 2025', 'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f', 'name': 'Any 2025'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Companyies aèries', 'id': '33666acc-21ac-43c7-8962-bad8c2b1b9b8', 'name': 'Companyies aèries'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Països', 'id': '20960c98-7f6e-4670-8068-bd113051b241', 'name': 'Països'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'Vols', 'id': 'd5418719-80fe-462f-ab53-00145a28e06b', 'name': 'Vols'}], 'ODS_Principal_agenda_2030': 'ODS 9: Industria, innovació i infraestructures', 'fecha_publicacion': '2024-05-30', 'ODS_Colateral2_agenda_2030': 'N/A', 'ODS_Colateral1_agenda_2030': 'N/A', 'license_id': 'CC-BY-4.0', 'hide_url': 'No', 'relationships_as_subject': [], 'license_title': 'Creative Commons Attribution 4.0', 'groups': [], 'num_resources': 7, 'organization': {'code': 'transport', 'display_name': 'Transport', 'description': 'Transport', 'parent': {'code': 'entorn-urba', 'display_name': 'Ciutat i serveis', 'description': 'City and Services', 'created': '2017-01-24T16:55:08.867299', 'package_count': 0, 'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-ciutat-i-serveis', 'description_translated': {'ca': 'Ciutat i serveis', 'en': 'City and Services', 'es': 'Ciudad y servicios'}, 'name': 'entorn-urba', 'is_organization': True, 'state': 'active', 'image_url': 'bcn-icon2-ciutat-i-serveis', 'groups': [], 'type': 'organization', 'title': 'City and Services', 'revision_id': 'effe3c8f-e810-4d94-b6a8-3e57540c0802', 'title_translated': {'ca': 'Ciutat i serveis', 'en': 'City and Services', 'es': 'Ciudad y servicios'}, 'num_followers': 0, 'id': 'd80eb926-faec-4e14-98b9-8c3f0d295977', 'approval_status': 'approved'}, 'created': '2017-01-24T16:55:06.928326', 'package_count': 74, 'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-transports-publics', 'tematica_nti': 'transporte', 'description_translated': {'ca': 'Transport', 'en': 'Transport', 'es': 'Transporte'}, 'name': 'transport', 'is_organization': True, 'state': 'active', 'image_url': 'bcn-icon-transports-publics', 'groups': [{'capacity': 'public', 'name': 'entorn-urba'}], 'type': 'organization', 'title': 'Transport', 'revision_id': 'f2d2031d-7973-42f6-8437-d6ee8ad98609', 'title_translated': {'ca': 'Transport', 'en': 'Transport', 'es': 'Transporte'}, 'num_followers': 0, 'id': '50bee103-b517-4728-838e-fc0d6b19e91f', 'approval_status': 'approved'}, 'name': 'transitaeri_flightradar_ppal_pais', 'url': None, 'notes': 'Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries', 'owner_org': '50bee103-b517-4728-838e-fc0d6b19e91f', 'load_type': 'link_intern_desde_font_interna', 'api': 'Yes', 'license_url': 'https://creativecommons.org/licenses/by/4.0/', 'historical': 'Yes', 'title': 'Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries', 'revision_id': 'd79157fb-be20-4e7c-bb5f-61cd55d7713d', 'extras': [{'key': '01.Data_Referencia', 'value': 'Data de les dades'}, {'key': '02.Codi_Pais', 'value': 'Codi del pais'}, {'key': '03.Nom_Pais', 'value': 'Nom del pais'}, {'key': '04.Nombre_Vols', 'value': 'Nombre de vols'}]}

Status code de package_show: 200

Detalles completos del datase:

### 2. 
De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON.

Dataset seleccionado:

	•	Nombre: transitaeri_flightradar_ppal_pais
	•	ID: 6ea9c163-e907-49fc-b916-bdddd1448e9e
	•	Título:Número de operaciones de aeronaves del aeropuerto Josep Tarradellas Barcelona-El Prat por principales países de destino u origen
	•	Formatos disponibles: CSV (2019, 2020, 2021, 2022, 2023, 2024, 2025)
	•	Motivo de selección: Tiene recursos accesibles en CSV, adecuados para descarga directa y análisis con pandas

### 3. 
Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search para:

* Recuperar al menos 100 registros.

In [41]:
BASE = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search" # endpoint base de Open Data BCN

RESOURCE_ID = "daaf92f4-8879-40f0-bc35-d550f1f9582a" # CSV del aeropuerto 2025

params = {"resource_id": RESOURCE_ID, # parámetros de la consulta: id
          "limit": 100}  # 100 registros

respuesta = requests.get(BASE, params=params) # petición GET

print("Status code:", respuesta.status_code) # el código de estado

data = respuesta.json() # convertir a JSON

print("Success:", data.get("success")) # comprobar si la API ha respondido correctamente a nivel lógico

registros = data["result"]["records"] # extraer los registros

print("Número de registros recuperados:", len(registros)) # cantidad de registros recuperados

print("\nPrimer registro:")
print(registros[0])

Status code: 200
Success: True
Número de registros recuperados: 100

Primer registro:
{'Data_Referencia': '2025-01-01T00:00:00', 'Nom_Pais': 'Espanya', 'Nombre_Vols': '230', '_id': 1, 'Codi_Pais': '1'}

### 4. 
Convierte los resultados a un DataFrame.

In [42]:
df = pd.DataFrame(registros) # convertir la lista en un DataFrame

print("Primeras filas del DataFrame:")
display(df.head())

print("\nDimensiones del DataFrame (filas, columnas):", df.shape)
print("\nNombres de columnas:")
print(df.columns)

Primeras filas del DataFrame:

       Data_Referencia    Nom_Pais Nombre_Vols  _id Codi_Pais
0  2025-01-01T00:00:00     Espanya         230    1         1
1  2025-01-01T00:00:00      Itàlia         100    2         2
2  2025-01-01T00:00:00  Regne Unit          71    3         3
3  2025-01-01T00:00:00      França          83    4         4
4  2025-01-01T00:00:00    Alemanya          48    5         5

Dimensiones del DataFrame (filas, columnas): (100, 5)

Nombres de columnas:
Index(['Data_Referencia', 'Nom_Pais', 'Nombre_Vols', '_id', 'Codi_Pais'], dtype='object')

### 5. 
Guarda DataFrame en un archivo .csv.

In [43]:
archivo = "aeropuerto_bcn_dataset.csv" # nombre

df.to_csv(archivo, index=False, encoding="utf-8") # guardar el Df en un archivo CSV sin índice y con la codificación que asegura la correcta representación de caracteres especiales

print(f"Archivo CSV guardado correctamente con el nombre: {archivo}")

Archivo CSV guardado correctamente con el nombre: aeropuerto_bcn_dataset.csv